feat: new command mapper structure
SonyPradana/php-library pull request #227
Opened 2023-10-27 14:53 UTC by SonyPradana

2023-10-27 14:53 UTC, SonyPradana commented
add more test soon

2023-10-27 15:16 UTC, anggerpradana requested changes

2023-10-27 15:16 UTC, anggerpradana commented on src/System/Integrate/ValueObjects/CommadMap.php
> +     * @return array<string, string|bool|int|null>
ok if default options get from command so we need data type also in command

2023-10-27 15:16 UTC, anggerpradana commented on src/System/Integrate/ValueObjects/CommadMap.php
> +            return $this->command['match'];
also this

2023-10-29 23:06 UTC, anggerpradana approved these changes

2023-10-29 23:07 UTC, merged