refactor: rewrite model (MyModel and MyCRUD)
SonyPradana/php-library pull request #285
Opened 2024-02-18 14:03 UTC by SonyPradana

refactor model, combine MyModel and MYCRUD

2024-02-27 02:08 UTC, SonyPradana commented on src/System/Database/MyModel/Collection.php
> +<?php
ambigus with original `Collection`, try to changes `ModelCollection` or other.

2024-02-27 16:52 UTC, SonyPradana commented
finishing...
give method and parameters good documents

2024-03-01 07:00 UTC, anggerpradana reviewed
better ux

2024-03-01 07:00 UTC, anggerpradana commented on src/System/Database/MyModel/Model.php
> +    public function hasOne(string $table, string $ref = 'id')
how about return as model, and `Model::class` instead of `table_nama`

2024-03-01 07:06 UTC, anggerpradana requested changes

2024-03-01 07:06 UTC, anggerpradana commented on src/System/Database/MyModel/Model.php
> +    public function hasMany(string $table, string $ref = 'id')
how about return as model, and `Model::class` instead of `table_name`

2024-03-01 07:06 UTC, anggerpradana commented on src/System/Database/MyModel/Model.php
> +     * Get column change status (compare with fresh record).
reserves value

2024-03-04 08:17 UTC, anggerpradana approved these changes

2024-03-04 08:24 UTC, merged