feat: cache
SonyPradana/php-library pull request #378
Opened 2024-09-07 16:35 UTC by SonyPradana

| Q            | A                                                         |
|--------------|-----------------------------------------------------------|
| Is bugfix?   | **No**                                              |
| New feature? | **Yes**                                              |
| Breaks BC?   | **No**                                              |
| Fixed issues | |

------
Cache manager

2024-09-08 03:35 UTC, SonyPradana reviewed
consider pass php stan before continue (write test)

2024-09-08 03:35 UTC, SonyPradana commented on split-repo.php
> +        'sonypradana/Cache' => '/src/System/Cache/',
use lowercase

2024-09-08 03:35 UTC, SonyPradana commented on src/System/Cache/CacheInterface.php
> +    public function setMultiple(iterable $values, int|\DateInterval|null $ttl = null);
forgot return type

2024-09-08 03:35 UTC, SonyPradana commented on src/System/Cache/CacheManager.php
> +        return $this->driver()->{$method}($parameters);
use parameter destruction

2024-09-08 12:02 UTC, SonyPradana commented
add
- [ ] increment and decrement
- [ ] remember
- [ ] mtime / meta data (make time)

2024-09-10 13:16 UTC, anggerpradana requested changes

2024-09-10 13:16 UTC, anggerpradana commented on src/System/Support/Facades/Cache.php
> +<?php
more doc

2024-09-11 02:38 UTC, merged